### ISSUE TITLE
Adauga paginile pentru furnizori si clienti

### ISSUE THREAD

**Issue by alin1k** [alin1k/rostil-tehnoserv-frontend#10]
## Descriere issue
Din dropdown, atunci cand dai click pe cele doua butoane sa te trimita pe pagina corespunzatoare.

![image](https://github.com/user-attachments/assets/de267fe4-2cc5-492d-b928-7082adf92e76)
![image](https://github.com/user-attachments/assets/fa85d797-ded0-4e40-bfc1-5aee50174733)

Se face asemanator cu paginile de oferte. (vezi codul)

Continutul paginii nu trebuie sa fie prea complicat. Pune ceva placeholder momentan.

## Documentatie necesara

https://nextjs.org/docs/app/building-your-application/routing

**Comment by alin1k** [comment]
@CosminPro02 nu ai adaugat pagina pt clienti.
Foloseste acelasi branch [10-adauga-paginile-pentru-furnizori-si-clienti](https://github.com/alin1k/rostil-tehnoserv-frontend/tree/10-adauga-paginile-pentru-furnizori-si-clienti)

**Comment by alin1k** [comment]
Poti sa pui doar un text pe pagina de clienti (cum e si pentru oferte), nu are rost sa faci inca un form

**Comment by CosminPro02** [comment]
Inca nu m-am apucat si de aia de clienti

**Comment by alin1k** [comment]
aa, ok. daca mai e ceva ce nu apuci sa termini din task-ul asta sau urmatoarele, sa nu ii dai merge in dev. Poti sa dai commit local si push pe Github dar nu si merge

**Comment by CosminPro02** [comment]
A ok

**Comment by CosminPro02** [comment]
GATA
