### ISSUE TITLE
Adauga ca meniul sa apara pe hover mouse nu pe click.

### ISSUE THREAD

**Issue by VictorOnose** [alin1k/rostil-tehnoserv-frontend#23]
Pe meniul de actiuni, se va adauga hover in loc de click mouse.

**Comment by alin1k** [comment]
@VictorOnose @CosminPro02 

Ce ziceti daca am folosi asta in loc de DropDown menu? https://ui.shadcn.com/docs/components/navigation-menu
Credeti ca ar fi o idee buna sa punem si ceva despre ce face fiecare buton in parte? Sau sa ignoram treaba aia si vedem ce iese?
Daca nu as putea sa ma uit si peste fisierela de la DropDown si sa vad daca pot sa-i fac ceva sa se deschida cand dai hover.

**Comment by CosminPro02** [comment]
Eu zic ca ar merge

**Comment by VictorOnose** [comment]
Ar fi mai fain sa arate asa. Eu zic sa incercam prima data sa vedem cum arata normal, iar apoi cu detalii, si ne decidem apoi cum arata mai estetic.
