### ISSUE TITLE
Adaugare  sweetAlert2 🥹🥹🥹

### ISSUE THREAD

**Issue by CosminPro02** [alin1k/rostil-tehnoserv-frontend#24]

**Comment by alin1k** [comment]
unde? cand sa apara? ce apare acum?
propun sa folosim alerta din shadcn: https://ui.shadcn.com/docs/components/alert-dialog
mai fa un issue te rog si da mai multe detalii 🙏

**Comment by CosminPro02** [comment]
@alin1k am vrut sa adaug  niste alerte atunci cand campurile sunt goale , sau atunci cand vrei sa stergi din lista si ca sa arate mai bine am vrut sa adaug asta sweetAlert2 doar ca dupa ce ii dadeam npm install sweetAlert2 dadea ceva eroare in legatura cu versiunea de react si voiam sa te uiti si tu putin

**Comment by CosminPro02** [comment]
dar daca e folosim si astea de pe shadcn , alea erau destul de usor de customizat doar
