### ISSUE TITLE
Formular de adaugare oferte

### ISSUE THREAD

**Issue by alin1k** [alin1k/rostil-tehnoserv-frontend#30]
## Descriere

A se adauga un formular de adaugare oferte. Acesta sa contina doar numele ofertei, si clientul (care poate fi selectat din clientii care deja exista). De asemenea sa se adauge in informatiile salvate si data in care a fost creata oferta. Aceasta data se va numi data ultimei modificari si va tine salvata data de la ultima modificare.

## Context aditional

Trebuie asteptat dupa #32

**Comment by CosminPro02** [comment]
Formularul nu ar trebui sa contina si un input in care sa selectam ce iteme sa includa oferta + un input in care sa se adauge pretul oferei?

**Comment by alin1k** [comment]
chestia aia o sa o adaugam atunci cand apesi pe editeaza oferta. exact cum este si in demo. Pretul ofertei este calculat automat dupa pretul produselor din oferta

zic sa lasam adaugarea de produse in oferta dupa ce facem viza 2 ca nu cred ca avem destul timp.

O sa iti scriu zilele viitoare despre cum o sa facem formularul asta.

**Comment by alin1k** [comment]
@CosminPro02 Poti sa te apuci sa faci formularul pls, cand termini ii dai push si il lasi asa fara sa dai merge. ms frms

**Comment by CosminPro02** [comment]
@alin1k daca poti sa te uiti pe branch-ul issuelui , am adaugat formul pentru adaugare a ofertei si in mare parte logica , nu stiu sigur daca funtioneaza exact  cum trebuie deoarece nu apare niciun client in lista de selectat ( posibil ca nu am implementat eu mine context sau e ceva la modul in care se salveaza datele in local storage ) , scz ca m-am apucat mai tarziu de asta dar n-am avut timp mai repede

**Comment by alin1k** [comment]
@CosminPro02 ai uitat de data, o rezolvam dupa viza 2
