### ISSUE TITLE
Modificare formulare de adaugare

### ISSUE THREAD

**Issue by alin1k** [alin1k/rostil-tehnoserv-frontend#40]
## Descriere a ceea ce este pana acum

Formularele de adaugare furnizor si client ocupa mult spatiu din pagina lor.

## Descriere a ceea ce se vrea

Pentru formularele de adaugare, sa fie ca un fel de pop-up care apare atunci cand apesi un buton

## Context additional

Se poate face ceva folosind: https://ui.shadcn.com/docs/components/dialog

**Comment by alin1k** [comment]
@VictorOnose il vr tu?

**Comment by VictorOnose** [comment]
il iau eu
